name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    name: windows
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Install libvips   shell: pwsh   run: choco install libvips-cpp -y

      - name: Set env
        shell: pwsh
        run: |
          echo "CGO_ENABLED=1" >> $env:GITHUB_ENV
          echo "GOEXPERIMENT=jsonv2" >> $env:GITHUB_ENV

      - name: Build project
        shell: pwsh
        run: |
          go version
          go build ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser.windows.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 1
          GOEXPERIMENT: jsonv2
