name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: windows
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      # ---------------- CHECKOUT ----------------
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---------------- GO ----------------
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      # ---------------- DEPENDENCIES ----------------
      - name: Enable CGO
        shell: pwsh
        run: |
          echo "CGO_ENABLED=1" >> $env:GITHUB_ENV

      # ---------------- BUILD ----------------
      - name: Build
        run: go build ./...

      # ---------------- GORELEASER ----------------
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser.windows.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 1
